version: '1.25.0'

services:
  web:
    image: narasimha8780/propvrtask:latest
    ports:
      - "80:80"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
